INSERT INTO cliente (nombre, apellido, email, create_at) VALUES ("Andres","Guzman","asas@asas.com","2018-01-01");
INSERT INTO cliente (nombre, apellido, email, create_at) VALUES ("dff","trtrtrt","awwa@asas.com","2018-01-01");
INSERT INTO cliente (nombre, apellido, email, create_at) VALUES ("yfufyuf","swsww","erer@asas.com","2018-01-01");
INSERT INTO cliente (nombre, apellido, email, create_at) VALUES ("Anbnvbnvdres","rerere","asas@asas.com","2018-01-04");
INSERT INTO mascota (nombre, fecha_nacimiento) VALUES ("Cheddar", "1017-01-09");
INSERT INTO vehiculo (marca, modelo) VALUES ("Chevrolet", "LUV");
INSERT INTO marca (nombre) VALUES ("Chevrolet");
INSERT INTO marca (nombre) VALUES ("Toyota");
INSERT INTO marca (nombre) VALUES ("Susuki");
INSERT INTO marca (nombre) VALUES ("Shelby");
INSERT INTO marca (nombre) VALUES ("Yamaha");
INSERT INTO marca (nombre) VALUES ("Subaru");